version: "3.8"

services:

  behance-crawler-app:
    image: 271217/felix-node-npm:1.3
    container_name: behance-crawler-app
    restart: unless-stopped
    volumes:
      - .:/opt
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - -c
      - |
        node index.js
    ports:
      - 3010:3000
      - 3013:3000
